version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/etc/mysql
      - mysql:/var/lib/mysql
    env_file:
        - variables.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - phalcon-compose

  memcached:
    image: memcached:1.4-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  
    networks:
      - phalcon-compose

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - phalcon-compose

  nginx-server:
    image: nginx
    volumes:
        - ./nginx:/etc/nginx
        - app-data:/app
    restart: on-failure
    ports:
        - 8083:80
    networks:
        - phalcon-compose

  phpfpm:
    image: suhelen/phalcon-fpm
    working_dir: /app
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
      - app-data:/app
    depends_on:
      - mysql
      - nginx-server
    env_file:
      - variables.env
    networks:
      - phalcon-compose

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  app-data:
    driver: local

networks:
  phalcon-compose:
    driver: overlay
    ipam:
      config:
        - subnet: 172.29.0.0/24
