version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - ./conf/mysql:/etc/mysql
      - mysql:/var/lib/mysql
    env_file:
        - variables.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - phalcon-compose
    dns: &internal-dns
      - 172.16.1.150
      - 114.114.114.114

  memcached:
    image: memcached:1.4-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  
    networks:
      - phalcon-compose
    dns: *internal-dns

  redis:
    image: redis:3.2-alpine
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
      - redis:/data
    command: redis-server /etc/redis.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - phalcon-compose
    dns: *internal-dns

  shopnc:
    build: docker/shopnc
    image: magichuihui/shopnc:v1.0
    working_dir: /projects
    volumes:
      - ./conf/php56/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php56/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./projects:/projects
    depends_on:
      - mysql
    env_file:
      - variables.env
    networks:
      - phalcon-compose
    dns: *internal-dns

  nginx-server:
    image: openresty/openresty:1.13.6.1-centos
    volumes:
      - ./projects:/projects
      - ./conf/nginx:/usr/local/openresty/nginx/conf
    restart: on-failure
    depends_on:
      - shopnc
    ports:
        - 80:80
    networks:
        - phalcon-compose
    dns: *internal-dns

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  phalcon-compose:
    driver: overlay
    ipam:
      config:
        - subnet: 172.29.0.0/24
